### ISSUE TITLE
Outbound AC Transit Transbay Routes 

### ISSUE THREAD

**Issue by DavidOry** [BayAreaMetro/travel-model-two-networks#14]
Everything looks good except the outbound AC Transit transbay routes (the routes with letters) appear to be missing. Meaning, if I look in the Evening Commute period, I do not see the outbound routes. Can you please have a look at this?

**Comment by i-am-sijia** [comment]
There's no feasible path in the current drive network for routes coming out of the Transbay Temporary Terminal.  See below for the links with `drive_access = 1`.  We are missing two drive links from osm node `890045140` to `5372055804`, to `890045129`.  It is because link from node `5372055804` to node `890045129` is `cycleway` (default to non-drive), and `service` link from node `890045140` to `5372055804` becomes drive dead-end.  

I will make those two links both `service`, and drive-able.  Maybe later on we can use project card to make them `bus_only`.

![image](https://user-images.githubusercontent.com/28812722/93718710-d998a500-fb4b-11ea-9963-edce3bd389ef.png)

**Comment by i-am-sijia** [comment]
AC Transit (routes with letters) evening outbound routes.

![image](https://user-images.githubusercontent.com/28812722/93720945-9134b380-fb5a-11ea-9b6f-18595c0d727f.png)

**Comment by i-am-sijia** [comment]
WestCAT Lynx outbound routes.

![image](https://user-images.githubusercontent.com/28812722/93720963-b32e3600-fb5a-11ea-8656-7b7662a001d6.png)

**Comment by DavidOry** [comment]
> There's no feasible path in the current drive network for routes coming out of the Transbay Temporary Terminal. See below for the links with `drive_access = 1`. We are missing two drive links from osm node `890045140` to `5372055804`, to `890045129`. It is because link from node `5372055804` to node `890045129` is `cycleway` (default to non-drive), and `service` link from node `890045140` to `5372055804` becomes drive dead-end.
> 
> I will make those two links both `service`, and drive-able. Maybe later on we can use project card to make them `bus_only`.
> 
> ![image](https://user-images.githubusercontent.com/28812722/93718710-d998a500-fb4b-11ea-9963-edce3bd389ef.png)

@gshivaraman Can you please make a project card to make these links bus only?
